### ISSUE TITLE
$documentRoot

### ISSUE THREAD

**Issue by Lomacar** [lencioni/SLIR#35]
Why is this variable set to 

`rtrim(realpath(preg_replace('`' . preg_quote($_SERVER['PHP_SELF']) . '$`', '', $_SERVER['SCRIPT_FILENAME'])), '/');`

and not

`$_SERVER['DOCUMENT_ROOT'];`

I had to change it in order to make it work on my site. I don't want to have to hard code it in the config file because it changes depending on where it is running (ie. local dev, production server).

If I leave it as the default then it tries to fetch images from

`/path/to/site/SLIR/index.php?/img/photo.jpg`

rather than

`/path/to/site/img/photo.jpg`

**Comment by Lomacar** [comment]
Umm. You may have changed that too soon. When I went from local to remote server I needed to switch back to the old method. I wish there was a way to make it just work, no matter what the server configuration. (The issue on the remote server is that I was running the site on a sub-domain, under a subfolder. So `$_SERVER['DOCUMENT_ROOT'];` was pointing to `server/path/html/` when I needed `server/path/html/new-site/`)

**Comment by ambroisemaupate** [comment]
As you said 

``` php
rtrim(realpath(preg_replace('' . preg_quote($_SERVER['PHP_SELF']) . '$', '', $_SERVER['SCRIPT_FILENAME'])), '/');
```

is the same as 

``` php
$_SERVER['DOCUMENT_ROOT'];
```

In your case, your are dealing with a sub-folder site and not a dedicated virtual-host. SLIR is built to use image path relatively to your virtual-host root. The solution is to use 2 different `slir-config.class.php` on dev and prod OR to create a virtual-host on your site which has `server/path/html/new-site` as document root.

`slir-config.class.php` is gitignored so that you can use a different one without modifying SLIR sources.

**Comment by Lomacar** [comment]
I did this in slirconfigdefaults.class.php and it now works in all environments for me.

    self::$documentRoot = $_SERVER['DOCUMENT_ROOT'];
        
    if(!is_file($documentRoot.$_SERVER['SCRIPT_NAME'])) {
        self::$documentRoot = rtrim(realpath(preg_replace('`' . preg_quote($_SERVER['PHP_SELF']) . '$`', '', $_SERVER['SCRIPT_FILENAME'])), '/');
    }`
