### ISSUE TITLE
Is SLIR deprecated in favor of Intervention Request?

### ISSUE THREAD

**Issue by cmeeren** [lencioni/SLIR#38]
On [a fork of this project ](https://github.com/rezozero/slir) it says that "SLIR is now deprecated in favor of [ambroisemaupate/intervention-request](https://github.com/ambroisemaupate/intervention-request) library". Is this true? Should we use that instead?

**Comment by lencioni** [comment]
I haven't used that library before, so I can't comment on if it should be used in favor of SLIR. I don't personally have plans on making updates to SLIR at this time, but if you or someone else wanted to carry the torch I would support that.

**Comment by cmeeren** [comment]
Sorry, I don't have the time and my PHP skills are rudimentary. I barely managed #37 by copying existing code... :innocent: Thanks though!

**Comment by ambroisemaupate** [comment]
Hi, I choose to stop supporting SLIR because I think it’s not future proof. I found this awesome library http://image.intervention.io/ and I decided to create a wrapper to use it as SLIR, so I created https://github.com/ambroisemaupate/intervention-request. You’ll find the same URL scheme and a caching mechanism but the foundations are built on _Composer_ dependencies and PSR-4 coding standards. It's built to be extensible.
